/* ----------------------------------------------------------------------------
 * IBM Confidential

   IBM Wireless M2M Platform

   (C)Copyright IBM Corp. 2009, 2010, 2011

   All Rights Reserved.

   File Name: bs_cfg.h

   Change Activity:

   Date             Description of Change                            By
   -----------      ---------------------                            --------
   12-May 2011       Created                                         Zhu, Zhenbo

   ----------------------------------------------------------------------------
   PROLOG END TAG zYx                                                         */

#ifndef __FRM_CFG_H_
#define __FRM_CFG_H_

#include <sys/types.h>

#define MAX_PARAM_NUM 256
#define MAX_COMPONENT_NUM 8

#define MAX_KEY_LEN 128
#define MAX_VALUE_SIZE 128 /* value size in byte */

/** Use MACRO define for these, do not like enum */
typedef int (*bs_param_cb) (int type, int len, void * p_buf);

/* key type */
#define VAL_INTEGER 0
#define VAL_STRING 1
#define VAL_FLOAT 2

/* COMPONENT ID (unused) */
#define COMM_PARAM_ID 0
#define MAC_PARAM_ID 1
#define PHY_PARAM_ID 2
#define RRU_PARAM_ID 3
#define AGENT_PARAM_ID 4
#define PERF_PARAM_ID 5
#define DEBUG_PARAM_ID 6

/* parameters are list here with their args. */
/* (key_name, component_name, key_index(unused), type, min value, max value) */
/* need default value? */

#define PARAM_KEYS    \
    CONVERT_KEY (MY_MAC, COMM, 0, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (INTERFERENCE_ACTIVE, COMM, 1, VAL_STRING, 0, 0, cfg_update_phy_interference)    \
    CONVERT_KEY (NUM_DL_INTERFERENCE, COMM, 2, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (NUM_UL_INTERFERENCE, COMM, 3, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (TX_ANTENNA_NUM, COMM, 4, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (SYMBOL_NUM_IN_DL_FRAME, COMM, 5, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RX_ANTENNA_NUM, COMM, 6, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (BS_ID, COMM, 7, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (SYMBOL_NUM_IN_UL_FRAME, COMM, 8, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (WIRELESS_INTERNAL_Q_IDBASE, COMM, 9, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CS_HASH_TABLE, COMM, 10, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (BS_IFDEV_NAME, COMM, 11, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (BS_IP_SUBNET, COMM, 12, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (UART_DEV_NAME, COMM, 13, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (CONTINUE_FRM_NUM, COMM, 14, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (INITIAL_SENSING_ENABLE, COMM, 15, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PERIODIC_SENSING_ENABLE, COMM, 16, VAL_INTEGER, 0, 0, cfg_update_ps_enable_cb)    \
    CONVERT_KEY (RANGING_ENABLE, COMM, 17, VAL_INTEGER, 0, 0, NULL)    \
    \
    CONVERT_KEY (DL_EXP_DURATION, MAC, 0, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_MM_DELAY, MAC, 1, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_MM_MAX_SIZE, MAC, 2, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_MM_NUM_TYPE_PER_CID, MAC, 3, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_MM_MIN_TYPE, MAC, 4, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (MAX_VALID_BASIC_CID, MAC, 5, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (MAX_VALID_UGS_PER_SS, MAC, 6, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (MAX_VALID_BE_PER_SS, MAC, 7, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (TX_UGS_CID_OFFSET, MAC, 8, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (TX_BE_CID_OFFSET, MAC, 9, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_MM_NUM_BWR, MAC, 10, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_ARQ_WINDOW_SIZE, MAC, 11, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_ARQ_BLK_SIZE, MAC, 12, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_ARQ_LOSS_PERCENT, MAC, 13, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_ARQ_CID_PERCENT, MAC, 14, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_IS_FRAG_ENABLED, MAC, 15, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_IS_PACK_ENABLED, MAC, 16, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_IS_FRAG_ENABLED, MAC, 17, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_IS_PACK_ENABLED, MAC, 18, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (NUM_ATTACHED_PROCS, MAC, 19, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_MCS, MAC, 20, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_MCS, MAC, 21, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_CBR_PACKET_SIZE, MAC, 22, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_CBR_PACKET_DELAY, MAC, 23, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_CBR_PACKET_SIZE, MAC, 24, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_CBR_PACKET_DELAY, MAC, 25, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PERF_ENABLED_BLOCKS, MAC, 26, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (BIND_PROC_INDEX, MAC, 27, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (FHDC_FLAG, MAC, 28, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_STC_MATRIX_TYPE, MAC, 29, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_STC_MATRIX_TYPE, MAC, 30, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (MAX_RANGING_POWER_THD, MAC, 31, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (KEY_LIFE_DURATION, MAC, 32, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (KEY_GRACE_TIME, MAC, 33, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (KEY_DELTA_ADD, MAC, 34, VAL_STRING, 0, 0, NULL)    \
    \
    CONVERT_KEY (PHY_BANDWIDTH, PHY, 0, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_OFDM_FS, PHY, 1, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_OVERSAMPLING, PHY, 1, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_MULTIPLE_ZONE, PHY, 2, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_FRAME_IDX, PHY, 3, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_SYMBOL_OFFSET, PHY, 4, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_FIRST_ZONE, PHY, 5, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_MIMO_MODE, PHY, 6, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_ZONE_LEN, PHY, 7, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_PERMUTATION_TYPE, PHY, 8, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_OFDMA_NFFT, PHY, 9, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_OFDMA_G, PHY, 10, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (PHY_CCD_NUM, PHY, 11, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DL_PERMBASE, PHY, 12, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_MAX_CELLNUM, PHY, 13, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_MAX_SEGNUM, PHY, 14, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_PRBS_ID, PHY, 15, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_PILOT_INSERT, PHY, 16, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_PREAMBLE_IDX, PHY, 17, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_PREAMBLE_GUARD_BAND, PHY, 18, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_PREAMBLE_MAX_RUN_IDX, PHY, 19, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (FCH_BITMAP, PHY, 20, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (PHY_STC_RATE, PHY, 21, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_STCLAYER_NUM, PHY, 22, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_CODING_TYPE, PHY, 23, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_FRAME_INC, PHY, 24, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_UL_ZONE_BEGIN, PHY, 25, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_UL_ZONE_LEN, PHY, 26, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_UL_PERMUTATION_TYPE, PHY, 27, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_UL_PERMBASE, PHY, 28, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_BITMAP, PHY, 29, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (PHY_RANGING_SYMOFFSET, PHY, 30, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_RANGING_SUBCHOFFSET, PHY, 31, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_RANGING_SYM, PHY, 32, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_RANGING_SUBCH, PHY, 33, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_UL_MIMO_MODE, PHY, 34, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PHY_UL_CODING_TYPE, PHY, 35, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (DL_SYMBOL_PER_SLOTSYMBOL, PHY, 36, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (UL_SYMBOL_PER_SLOTSYMBOL, PHY, 37, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RANGING_THRESHOLD, PHY, 40, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (IR_HO_CODE_SET_NUM, PHY, 41, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (IR_HO_CODE_SET, PHY, 42, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (PR_BR_CODE_SET_NUM, PHY, 43, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PR_BR_CODE_SET, PHY, 44, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (CALIBRATE_ANALOG_POWER0, PHY, 45, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CALIBRATE_DIGITAL_POWER0, PHY, 46, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CALIBRATE_ANALOG_POWER1, PHY, 47, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CALIBRATE_DIGITAL_POWER1, PHY, 48, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (EXPECT_ANALOG_POWER, PHY, 49, VAL_STRING, 0, 0, cfg_update_ranging_exp_power)    \
    CONVERT_KEY (CALIBRATE_DIGTAL_GAIN0, PHY, 50, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (CALIBRATE_DIGTAL_GAIN1, PHY, 51, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (IR_SYMBOL_OFFSET, PHY, 52, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PR_SYMBOL_OFFSET, PHY, 53, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (IR_SUBCH_OFFSET, PHY, 54, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PR_SUBCH_OFFSET, PHY, 55, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PERIODIC_SENSING_DURATION, PHY, 56, VAL_INTEGER, 0, 0, cfg_update_ps_duration)    \
    CONVERT_KEY (INIT_SCAN_FREQ_NUM, PHY, 57, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (SCAN_STEP, PHY, 58, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (SCAN_CENTER_FREQ, PHY, 59, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (DEFAULT_WORKING_FREQ, PHY, 60, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (INITIAL_SENSING_ENABLE, PHY, 61, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (INITIAL_SENSING_POLICY, PHY, 62, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (IS_NFFT, PHY, 63, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RANGING_FILE_PATH, PHY, 64, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (PHY_DEBUG_PATH, PHY, 65, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (SOFTBIT_THRESHOLD, PHY, 66, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (SOFTBIT_SHIFT, PHY, 67, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (PERIODIC_SENSING_THD, PHY, 68, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (INITIAL_SENSING_THD, PHY, 69, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (RANGING_ALGORITHMS, PHY, 70, VAL_INTEGER, 0, 0, cfg_update_ranging_algorithms)    \
    CONVERT_KEY (RANGING_SNR_THRESHOLD, PHY, 71, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (SCAN_BW, PHY, 72, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (SCAN_POWER, PHY, 73, VAL_INTEGER, 0, 0, NULL)    \
    \
    CONVERT_KEY (BBU_NIC_IP, RRU, 0, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (RRU_NIC_IP, RRU, 1, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (BBU_NIC_DATA_PORT, RRU, 2, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_NIC_DATA_PORT, RRU, 3, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_NIC_MASK, RRU, 4, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (RRU_NIC_IF, RRU, 5, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (BBU_SERVER_ID, RRU, 6, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (BBU_TCP_PORT, RRU, 7, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_ID, RRU, 8, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_BROADCAST_IP, RRU, 9, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (AGENT_HEARTBEAT_TIMEOUT, RRU, 10, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (GAIN_TX, RRU, 11, VAL_FLOAT, 0, 0, NULL)    \
    CONVERT_KEY (ADVANCED_CMD_TIME, RRU, 12, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CHAN1_POWER_VALUE, RRU, 13, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CHAN2_POWER_VALUE, RRU, 14, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (ENABLE_RRU_GPS, RRU, 16, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RRU_OUTPUT_POWER, RRU, 17, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CHAN1_PA_ENABLE, RRU, 18, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CHAN2_PA_ENABLE, RRU, 19, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (IS_RX_FRAME_LEN, RRU, 20, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RRU_RX_LEN, RRU, 21, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RRU_TX_LEN, RRU, 22, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (ENABLE_RRU_AGC, RRU, 23, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CH0_RX_PGC, RRU, 24, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CH1_RX_PGC, RRU, 25, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RRU_LONGITUDE, RRU, 26, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (RRU_LATITUDE, RRU, 27, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER0_ENABLE, RRU, 28, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER0_FREQ, RRU, 29, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER0_BW, RRU, 30, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER0_POWER, RRU, 31, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER1_ENABLE, RRU, 32, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER1_FREQ, RRU, 33, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER1_BW, RRU, 34, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER1_POWER, RRU, 35, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER2_ENABLE, RRU, 36, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER2_FREQ, RRU, 37, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER2_BW, RRU, 38, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER2_POWER, RRU, 39, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER3_ENABLE, RRU, 40, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER3_FREQ, RRU, 41, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER3_BW, RRU, 42, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (CARRIER3_POWER, RRU, 43, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_MAC, RRU, 44, VAL_STRING, 0, 0, NULL)    \
    CONVERT_KEY (RRU_BYTE_ORDER, RRU, 45, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_TTG, RRU, 46, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RRU_RTG, RRU, 47, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RRU_ETH_PKT_LEN, RRU, 48, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_SAMPLE_RATE, RRU, 49, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RRU_CARRIER_NUM, RRU, 50, VAL_INTEGER, 0, 0, NULL)    \
    \
    CONVERT_KEY (AGENT_SERVER_PORT, AGENT, 0, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (AGENT_IP, AGENT, 1, VAL_STRING, 0, 0, NULL)  \
    CONVERT_KEY (MONITOR_SERVER_PORT, AGENT, 2, VAL_INTEGER, 0, 0, NULL)    \
    \
    CONVERT_KEY (METRIC_UPDATE_DURATION, PERF, 0, VAL_INTEGER, 0, 0, NULL)    \
    CONVERT_KEY (RangingSuccessCount, PERF, 1, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (PerWmbDLThroughput, PERF, 2, VAL_FLOAT, 0, 0, NULL) \
    CONVERT_KEY (PerWmbULThroughput, PERF, 3, VAL_FLOAT, 0, 0, NULL) \
    CONVERT_KEY (PerConnDLThroughput, PERF, 4, VAL_FLOAT, 0, 0, NULL) \
    CONVERT_KEY (PerConnULThroughput, PERF, 5, VAL_FLOAT, 0, 0, NULL) \
    CONVERT_KEY (ULMgmtThroughput, PERF, 6, VAL_FLOAT, 0, 0, NULL) \
    CONVERT_KEY (DLMgmtThroughput, PERF, 7, VAL_FLOAT, 0, 0, NULL) \
    CONVERT_KEY (ConnectionCount, PERF, 8, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (CRCErrorCount, PERF, 9, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (PDUTotalCount, PERF, 10, VAL_INTEGER, 0, 0, NULL) \
    \
    CONVERT_KEY (FAKE_TX_TRACE_I0, DEBUG, 0, VAL_STRING, 0, 0, NULL) \
    CONVERT_KEY (FAKE_TX_TRACE_Q0, DEBUG, 1, VAL_STRING, 0, 0, NULL) \
    CONVERT_KEY (FAKE_TX_TRACE_I1, DEBUG, 2, VAL_STRING, 0, 0, NULL) \
    CONVERT_KEY (FAKE_TX_TRACE_Q1, DEBUG, 3, VAL_STRING, 0, 0, NULL) \
    CONVERT_KEY (FAKE_ULMAP_DURATION, DEBUG, 4, VAL_INTEGER, 0, 0, cfg_update_fake_ulmap_duration) \
    CONVERT_KEY (FAKE_ULMAP_UIUC, DEBUG, 5, VAL_INTEGER, 0, 0, cfg_update_fake_ulmap_uiuc) \
    CONVERT_KEY (FAKE_BER_MODE, DEBUG, 6, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (DUMP_UTIL_PATH, DEBUG, 7, VAL_STRING, 0, 0, NULL) \
    CONVERT_KEY (BER_RESET, DEBUG, 8, VAL_INTEGER, 0, 0, cfg_update_ber_reset)\
    CONVERT_KEY (FAKE_TX_TRACE_FRM_NUM, DEBUG, 9, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (FAKE_RX_TRACE_FRM_NUM, DEBUG, 10, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (RX_FRAME_LEN, DEBUG, 11, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (TX_FRAME_LEN, DEBUG, 12, VAL_INTEGER, 0, 0, NULL) \
    CONVERT_KEY (TEST_TX_ONLY, DEBUG, 13, VAL_INTEGER, 0, 0, NULL) \
  
struct param_unit
{
    char key_name[MAX_KEY_LEN];           /* key name. */
    char component_name[MAX_KEY_LEN];     /* component name */
    char value[MAX_VALUE_SIZE];
    unsigned int component_id;
    unsigned int type;
    char min_value[MAX_VALUE_SIZE];           /* Min. value */
    char max_value[MAX_VALUE_SIZE];           /* Max. value */
    unsigned int index;
    unsigned int active; /* if active (:1) or not (:0) */
    bs_param_cb f_cb;
    pthread_mutex_t param_mutex;
};

struct config_unit
{
    int total_param_num;           /* total parameters. */
};

int32_t init_global_param (char * file_name);

int32_t deinit_global_param (void);

/* use key first, index is also? */
int32_t get_global_param (char * key_name, void * value);

int32_t set_global_param (char * key_name, void * value);

int32_t update_global_param (char * key_name, void * value);

#endif /* __FRM_CFG_H_ */

