
BSPROC_ROOT=../bsproc

USE_PPC=0
OS = $(shell uname)
ifeq ($(OS), AIX)
 USE_PPC = 1
else
 MACHINE_NAME = $(shell uname -m)
 ifeq ($(firstword $(filter ppc64,$(MACHINE_NAME))),ppc64)
   USE_PPC = 1
 endif
endif

CC = gcc -g
CFLAGS = -I${BSPROC_ROOT}/include/phy -I${BSPROC_ROOT}/include -Wall -O3  -D_GNU_SOURCE
LDFLAGS = -lm
ifeq ($(USE_PPC), 1)
  # penguin: why it does not work with -m64
  CFLAGS += -maltivec -mabi=altivec -mcpu=power7 -mtune=power7 -DVSXOPT 
else
  CFLAGS += -DLOG_LEVEL=LOG_LEVEL_WARN -DSSE2OPT -m64 -msse2 -msse3 -mssse3 -D_BS_MONITOR_ -D_AMC_INTERLEAVER_ -D_SOFTBIT_TWO_ -DIPP_OPT_TEMP730 -W 
endif

all: ${TARGET}

${TARGET}: ${OBJS}
	$(CC) -o $@ $(CFLAGS) $(LDFLAGS) $^

.c.o:
	@$(RM) $@
	$(CC) -c $(CFLAGS) $<

test:
	./${TARGET}

clean:
	$(RM) *.o ${TARGET} 
