TARGET_SRC=cva_kernel.cpp
TARGET_NAME=cva_kernel

BASE_DIR=../../..

include makefile.footer

clean:
	/bin/rm -rf *.o *~ cva_kernel cva_kernel_base cva_kernel_trans cva_kernel_kernel cva_kernel*_simd cva_kernel*_sse 
